apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: sk-demo
  labels:
    name: redis-slave
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
  selector:
    name: redis-slave
